#!/bin/bash

function triggerError {
    echo -e "\033[31m$1\033[0m" 1>&2
    exit 1
}

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

command=$1

# Check if beep has been called correctly
allowed_commands=("setup" "provision")
if [[ ! ${allowed_commands[*]} =~ "$command" ]]; then
    if [ -z "$command" ]; then
        triggerError "Usage: ./superlumic [setup|provision]"
    else
        triggerError "Usage: ./superlumic [setup|provision], not $command"
    fi
fi

# The command is setup, so setup beep
if [[ "$command" == "setup" ]]; then

    # Install Ansible
    sudo easy_install pip
    sudo pip install ansible



fi
